// Copyright (c) 2024 Robert Hildebrandt. All rights reserved.
// >> AUTOGENERATED!!! << NO NOT MODIFY! >> Modifications will be overwritten!!
// ==== usize ====
//@ terminates true; assigns \nothing; exits false;
void debug_assert_usize_eq(usize x, usize y);
//@ terminates true; assigns \nothing; exits false; ensures x == y;
void assert_usize_eq(usize x, usize y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_usize_ne(usize x, usize y);
//@ terminates true; assigns \nothing; exits false; ensures x != y;
void assert_usize_ne(usize x, usize y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_usize_lt(usize x, usize y);
//@ terminates true; assigns \nothing; exits false; ensures x < y;
void assert_usize_lt(usize x, usize y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_usize_lte(usize x, usize y);
//@ terminates true; assigns \nothing; exits false; ensures x <= y;
void assert_usize_lte(usize x, usize y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_usize_gt(usize x, usize y);
//@ terminates true; assigns \nothing; exits false; ensures x > y;
void assert_usize_gt(usize x, usize y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_usize_gte(usize x, usize y);
//@ terminates true; assigns \nothing; exits false; ensures x >= y;
void assert_usize_gte(usize x, usize y);

// ==== ssize ====
//@ terminates true; assigns \nothing; exits false;
void debug_assert_ssize_eq(ssize x, ssize y);
//@ terminates true; assigns \nothing; exits false; ensures x == y;
void assert_ssize_eq(ssize x, ssize y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_ssize_ne(ssize x, ssize y);
//@ terminates true; assigns \nothing; exits false; ensures x != y;
void assert_ssize_ne(ssize x, ssize y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_ssize_lt(ssize x, ssize y);
//@ terminates true; assigns \nothing; exits false; ensures x < y;
void assert_ssize_lt(ssize x, ssize y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_ssize_lte(ssize x, ssize y);
//@ terminates true; assigns \nothing; exits false; ensures x <= y;
void assert_ssize_lte(ssize x, ssize y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_ssize_gt(ssize x, ssize y);
//@ terminates true; assigns \nothing; exits false; ensures x > y;
void assert_ssize_gt(ssize x, ssize y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_ssize_gte(ssize x, ssize y);
//@ terminates true; assigns \nothing; exits false; ensures x >= y;
void assert_ssize_gte(ssize x, ssize y);

// ==== int ====
//@ terminates true; assigns \nothing; exits false;
void debug_assert_int_eq(int x, int y);
//@ terminates true; assigns \nothing; exits false; ensures x == y;
void assert_int_eq(int x, int y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_int_ne(int x, int y);
//@ terminates true; assigns \nothing; exits false; ensures x != y;
void assert_int_ne(int x, int y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_int_lt(int x, int y);
//@ terminates true; assigns \nothing; exits false; ensures x < y;
void assert_int_lt(int x, int y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_int_lte(int x, int y);
//@ terminates true; assigns \nothing; exits false; ensures x <= y;
void assert_int_lte(int x, int y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_int_gt(int x, int y);
//@ terminates true; assigns \nothing; exits false; ensures x > y;
void assert_int_gt(int x, int y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_int_gte(int x, int y);
//@ terminates true; assigns \nothing; exits false; ensures x >= y;
void assert_int_gte(int x, int y);

// ==== ptr ====
//@ terminates true; assigns \nothing; exits false;
void debug_assert_ptr_eq(const void* x, const void* y);
//@ terminates true; assigns \nothing; exits false; ensures x == y;
void assert_ptr_eq(const void* x, const void* y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_ptr_ne(const void* x, const void* y);
//@ terminates true; assigns \nothing; exits false; ensures x != y;
void assert_ptr_ne(const void* x, const void* y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_ptr_lt(const void* x, const void* y);
//@ terminates true; assigns \nothing; exits false; ensures x < y;
void assert_ptr_lt(const void* x, const void* y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_ptr_lte(const void* x, const void* y);
//@ terminates true; assigns \nothing; exits false; ensures x <= y;
void assert_ptr_lte(const void* x, const void* y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_ptr_gt(const void* x, const void* y);
//@ terminates true; assigns \nothing; exits false; ensures x > y;
void assert_ptr_gt(const void* x, const void* y);
//@ terminates true; assigns \nothing; exits false;
void debug_assert_ptr_gte(const void* x, const void* y);
//@ terminates true; assigns \nothing; exits false; ensures x >= y;
void assert_ptr_gte(const void* x, const void* y);

