// Copyright (c) 2024 Robert Hildebrandt. All rights reserved.
// >> AUTOGENERATED!!! << NO NOT MODIFY! >> Modifications will be overwritten!!
#ifndef __FRAMAC__

// ==== usize ====
void debug_assert_usize_eq(usize x, usize y)
{
#if ENV_DEBUG
  assert_usize_eq(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_usize_eq(usize x, usize y)
{
  if(LIKELY(x == y))
    return;
  else
  __assert_failed__();
}
void debug_assert_usize_ne(usize x, usize y)
{
#if ENV_DEBUG
  assert_usize_ne(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_usize_ne(usize x, usize y)
{
  if(LIKELY(x != y))
    return;
  else
  __assert_failed__();
}
void debug_assert_usize_lt(usize x, usize y)
{
#if ENV_DEBUG
  assert_usize_lt(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_usize_lt(usize x, usize y)
{
  if(LIKELY(x < y))
    return;
  else
  __assert_failed__();
}
void debug_assert_usize_lte(usize x, usize y)
{
#if ENV_DEBUG
  assert_usize_lte(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_usize_lte(usize x, usize y)
{
  if(LIKELY(x <= y))
    return;
  else
  __assert_failed__();
}
void debug_assert_usize_gt(usize x, usize y)
{
#if ENV_DEBUG
  assert_usize_gt(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_usize_gt(usize x, usize y)
{
  if(LIKELY(x > y))
    return;
  else
  __assert_failed__();
}
void debug_assert_usize_gte(usize x, usize y)
{
#if ENV_DEBUG
  assert_usize_gte(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_usize_gte(usize x, usize y)
{
  if(LIKELY(x >= y))
    return;
  else
  __assert_failed__();
}
void debug_assert_usize_lte_lte(usize x, usize y, usize z)
{
#if ENV_DEBUG
  assert_usize_lte_lte(x, y, z);
#else
  (void)x; (void)y; (void)z;
#endif
}
void assert_usize_lte_lte(usize x, usize y, usize z)
{
  if(LIKELY(x <= y && y <= z))
    return;
  else
  __assert_failed__();
}
void debug_assert_usize_lte_lt(usize x, usize y, usize z)
{
#if ENV_DEBUG
  assert_usize_lte_lt(x, y, z);
#else
  (void)x; (void)y; (void)z;
#endif
}
void assert_usize_lte_lt(usize x, usize y, usize z)
{
  if(LIKELY(x <= y && y < z))
    return;
  else
  __assert_failed__();
}

// ==== ssize ====
void debug_assert_ssize_eq(ssize x, ssize y)
{
#if ENV_DEBUG
  assert_ssize_eq(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_ssize_eq(ssize x, ssize y)
{
  if(LIKELY(x == y))
    return;
  else
  __assert_failed__();
}
void debug_assert_ssize_ne(ssize x, ssize y)
{
#if ENV_DEBUG
  assert_ssize_ne(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_ssize_ne(ssize x, ssize y)
{
  if(LIKELY(x != y))
    return;
  else
  __assert_failed__();
}
void debug_assert_ssize_lt(ssize x, ssize y)
{
#if ENV_DEBUG
  assert_ssize_lt(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_ssize_lt(ssize x, ssize y)
{
  if(LIKELY(x < y))
    return;
  else
  __assert_failed__();
}
void debug_assert_ssize_lte(ssize x, ssize y)
{
#if ENV_DEBUG
  assert_ssize_lte(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_ssize_lte(ssize x, ssize y)
{
  if(LIKELY(x <= y))
    return;
  else
  __assert_failed__();
}
void debug_assert_ssize_gt(ssize x, ssize y)
{
#if ENV_DEBUG
  assert_ssize_gt(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_ssize_gt(ssize x, ssize y)
{
  if(LIKELY(x > y))
    return;
  else
  __assert_failed__();
}
void debug_assert_ssize_gte(ssize x, ssize y)
{
#if ENV_DEBUG
  assert_ssize_gte(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_ssize_gte(ssize x, ssize y)
{
  if(LIKELY(x >= y))
    return;
  else
  __assert_failed__();
}
void debug_assert_ssize_lte_lte(ssize x, ssize y, ssize z)
{
#if ENV_DEBUG
  assert_ssize_lte_lte(x, y, z);
#else
  (void)x; (void)y; (void)z;
#endif
}
void assert_ssize_lte_lte(ssize x, ssize y, ssize z)
{
  if(LIKELY(x <= y && y <= z))
    return;
  else
  __assert_failed__();
}
void debug_assert_ssize_lte_lt(ssize x, ssize y, ssize z)
{
#if ENV_DEBUG
  assert_ssize_lte_lt(x, y, z);
#else
  (void)x; (void)y; (void)z;
#endif
}
void assert_ssize_lte_lt(ssize x, ssize y, ssize z)
{
  if(LIKELY(x <= y && y < z))
    return;
  else
  __assert_failed__();
}

// ==== int ====
void debug_assert_int_eq(int x, int y)
{
#if ENV_DEBUG
  assert_int_eq(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_int_eq(int x, int y)
{
  if(LIKELY(x == y))
    return;
  else
  __assert_failed__();
}
void debug_assert_int_ne(int x, int y)
{
#if ENV_DEBUG
  assert_int_ne(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_int_ne(int x, int y)
{
  if(LIKELY(x != y))
    return;
  else
  __assert_failed__();
}
void debug_assert_int_lt(int x, int y)
{
#if ENV_DEBUG
  assert_int_lt(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_int_lt(int x, int y)
{
  if(LIKELY(x < y))
    return;
  else
  __assert_failed__();
}
void debug_assert_int_lte(int x, int y)
{
#if ENV_DEBUG
  assert_int_lte(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_int_lte(int x, int y)
{
  if(LIKELY(x <= y))
    return;
  else
  __assert_failed__();
}
void debug_assert_int_gt(int x, int y)
{
#if ENV_DEBUG
  assert_int_gt(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_int_gt(int x, int y)
{
  if(LIKELY(x > y))
    return;
  else
  __assert_failed__();
}
void debug_assert_int_gte(int x, int y)
{
#if ENV_DEBUG
  assert_int_gte(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_int_gte(int x, int y)
{
  if(LIKELY(x >= y))
    return;
  else
  __assert_failed__();
}

// ==== ptr ====
void debug_assert_ptr_eq(const void* x, const void* y)
{
#if ENV_DEBUG
  assert_ptr_eq(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_ptr_eq(const void* x, const void* y)
{
  if(LIKELY(x == y))
    return;
  else
  __assert_failed__();
}
void debug_assert_ptr_ne(const void* x, const void* y)
{
#if ENV_DEBUG
  assert_ptr_ne(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_ptr_ne(const void* x, const void* y)
{
  if(LIKELY(x != y))
    return;
  else
  __assert_failed__();
}
void debug_assert_ptr_lt(const void* x, const void* y)
{
#if ENV_DEBUG
  assert_ptr_lt(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_ptr_lt(const void* x, const void* y)
{
  if(LIKELY(x < y))
    return;
  else
  __assert_failed__();
}
void debug_assert_ptr_lte(const void* x, const void* y)
{
#if ENV_DEBUG
  assert_ptr_lte(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_ptr_lte(const void* x, const void* y)
{
  if(LIKELY(x <= y))
    return;
  else
  __assert_failed__();
}
void debug_assert_ptr_gt(const void* x, const void* y)
{
#if ENV_DEBUG
  assert_ptr_gt(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_ptr_gt(const void* x, const void* y)
{
  if(LIKELY(x > y))
    return;
  else
  __assert_failed__();
}
void debug_assert_ptr_gte(const void* x, const void* y)
{
#if ENV_DEBUG
  assert_ptr_gte(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_ptr_gte(const void* x, const void* y)
{
  if(LIKELY(x >= y))
    return;
  else
  __assert_failed__();
}
void debug_assert_ptr_lte_lte(const void* x, const void* y, const void* z)
{
#if ENV_DEBUG
  assert_ptr_lte_lte(x, y, z);
#else
  (void)x; (void)y; (void)z;
#endif
}
void assert_ptr_lte_lte(const void* x, const void* y, const void* z)
{
  if(LIKELY(x <= y && y <= z))
    return;
  else
  __assert_failed__();
}
void debug_assert_ptr_lte_lt(const void* x, const void* y, const void* z)
{
#if ENV_DEBUG
  assert_ptr_lte_lt(x, y, z);
#else
  (void)x; (void)y; (void)z;
#endif
}
void assert_ptr_lte_lt(const void* x, const void* y, const void* z)
{
  if(LIKELY(x <= y && y < z))
    return;
  else
  __assert_failed__();
}

// ==== cstr_eq ====
void debug_assert_cstr_eq(const char* x, const char* y)
{
#if ENV_DEBUG
  assert_cstr_eq(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_cstr_eq(const char* x, const char* y)
{
  if(LIKELY((strcmp(x,y) == 0)))
    return;
  else
  __assert_failed__();
}

// ==== bool_eq ====
void debug_assert_bool_eq(bool x, bool y)
{
#if ENV_DEBUG
  assert_bool_eq(x, y);
#else
  (void)x; (void)y;
#endif
}
void assert_bool_eq(bool x, bool y)
{
  if(LIKELY(x == y))
    return;
  else
  __assert_failed__();
}

#endif // __FRAMAC__
